/**
 * CuratedHadiths — Hand-picked, impactful hadiths organized by topic.
 * Same approach as QuranTopics.ts for Verse of the Day.
 * All hadiths are Sahih-grade from Bukhari and Muslim.
 * Arabic text is matn-only (no isnad). English is clean (no "Narrated X:" prefix).
 */

import { CuratedHadith, HadithTopic } from './HadithTypes';

export const HADITH_TOPICS: HadithTopic[] = [
    {
        id: 'kindness',
        name: 'Kindness & Compassion',
        hadiths: [
            {
                id: 'k1',
                arabicText: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
                englishText: 'The merciful are shown mercy by the Most Merciful. Show mercy to those on earth, and the One above the heavens will show mercy to you.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sunan Abu Dawud',
                reference: '4941',
                topic: 'Kindness & Compassion',
                reflection: 'Start today by showing one act of mercy to someone — a kind word, forgiveness, or helping hand.',
            },
            {
                id: 'k2',
                arabicText: 'مَنْ لا يَرْحَمْ لا يُرْحَمْ',
                englishText: 'Whoever does not show mercy will not be shown mercy.',
                narrator: 'Jarir ibn Abdullah',
                collection: 'Sahih al-Bukhari',
                reference: '7376',
                topic: 'Kindness & Compassion',
                reflection: 'Mercy is not weakness — it is the strength that attracts Allah\'s mercy in return.',
            },
            {
                id: 'k3',
                arabicText: 'إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ',
                englishText: 'Indeed, Allah is gentle and loves gentleness in all matters.',
                narrator: 'Aisha',
                collection: 'Sahih al-Bukhari',
                reference: '6927',
                topic: 'Kindness & Compassion',
                reflection: 'Gentleness transforms every situation — with family, at work, even in disagreements.',
            },
            {
                id: 'k4',
                arabicText: 'لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
                englishText: 'None of you truly believes until he loves for his brother what he loves for himself.',
                narrator: 'Anas ibn Malik',
                collection: 'Sahih al-Bukhari',
                reference: '13',
                topic: 'Kindness & Compassion',
                reflection: 'True faith goes beyond rituals — it means genuinely wanting good for others.',
            },
            {
                id: 'k5',
                arabicText: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
                englishText: 'Your smiling in the face of your brother is an act of charity.',
                narrator: 'Abu Dharr',
                collection: 'Jami at-Tirmidhi',
                reference: '1956',
                topic: 'Kindness & Compassion',
                reflection: 'The simplest acts of kindness carry the weight of charity in Islam.',
            },
            {
                id: 'k6',
                arabicText: 'إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ',
                englishText: 'Indeed, Allah has prescribed excellence (ihsan) in everything.',
                narrator: 'Shaddad ibn Aws',
                collection: 'Sahih Muslim',
                reference: '1955',
                topic: 'Kindness & Compassion',
                reflection: 'Excellence is not optional — Allah mandates doing everything with care and beauty.',
            },
            {
                id: 'k7',
                arabicText: 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
                englishText: 'Whoever relieves a believer of a hardship in this world, Allah will relieve him of a hardship on the Day of Resurrection.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2699',
                topic: 'Kindness & Compassion',
                reflection: 'Help someone through a tough time today — Allah will do the same for you when it matters most.',
            },
            {
                id: 'k8',
                arabicText: 'خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ',
                englishText: 'The best of people are those most beneficial to others.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'al-Mu\'jam al-Awsat',
                reference: '5787',
                topic: 'Kindness & Compassion',
                reflection: 'Your worth is measured by the positive impact you have on others\' lives.',
            },
            {
                id: 'k9',
                arabicText: 'فِي كُلِّ ذَاتِ كَبِدٍ رَطْبَةٍ أَجْرٌ',
                englishText: 'There is a reward in serving every living creature.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '2466',
                topic: 'Kindness & Compassion',
                reflection: 'Compassion extends beyond humans — even giving water to a thirsty animal earns reward.',
            },
        ],
    },
    {
        id: 'character',
        name: 'Good Character',
        hadiths: [
            {
                id: 'ch1',
                arabicText: 'إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وأَقْرَبِكُمْ مِنِّي مَجْلِسًا يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلاقًا',
                englishText: 'The most beloved of you to me and the closest to me on the Day of Resurrection are those with the best character.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'Jami at-Tirmidhi',
                reference: '2018',
                topic: 'Good Character',
                reflection: 'Your character is your legacy — it determines your rank with the Prophet ﷺ.',
            },
            {
                id: 'ch2',
                arabicText: 'إِنَّمَا بُعِثْتُ لأُتَمِّمَ صَالِحَ الأَخْلاقِ',
                englishText: 'I was only sent to perfect good character.',
                narrator: 'Abu Hurairah',
                collection: 'Musnad Ahmad',
                reference: '8939',
                topic: 'Good Character',
                reflection: 'The entire prophetic mission boils down to building excellent character.',
            },
            {
                id: 'ch3',
                arabicText: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
                englishText: 'Fear Allah wherever you are, follow a bad deed with a good deed to erase it, and treat people with good character.',
                narrator: 'Abu Dharr',
                collection: 'Jami at-Tirmidhi',
                reference: '1987',
                topic: 'Good Character',
                reflection: 'Three principles that cover your relationship with Allah and with people.',
            },
            {
                id: 'ch4',
                arabicText: 'مَا كَانَ الْفُحْشُ فِي شَيْءٍ إِلا شَانَهُ وَمَا كَانَ الْحَيَاءُ فِي شَيْءٍ إِلا زَانَهُ',
                englishText: 'Obscenity does not come into anything without disgracing it, and modesty does not come into anything without beautifying it.',
                narrator: 'Anas ibn Malik',
                collection: 'Jami at-Tirmidhi',
                reference: '1974',
                topic: 'Good Character',
                reflection: 'Your words and conduct either beautify or tarnish everything around you.',
            },
            {
                id: 'ch5',
                arabicText: 'إِنَّ مِنْ أَكْمَلِ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا وَأَلْطَفُهُمْ بِأَهْلِهِ',
                englishText: 'The most complete believers in faith are those with the best character and who are kindest to their families.',
                narrator: 'Abu Hurairah',
                collection: 'Jami at-Tirmidhi',
                reference: '1162',
                topic: 'Good Character',
                reflection: 'Faith and character are inseparable — the strongest faith produces the best manners.',
            },
            {
                id: 'ch6',
                arabicText: 'إِنَّكُمْ لَنْ تَسَعُوا النَّاسَ بِأَمْوَالِكُمْ وَلَكِنْ يَسَعُهُمْ مِنْكُمْ بَسْطُ الْوَجْهِ وَحُسْنُ الْخُلُقِ',
                englishText: 'You cannot encompass people with your wealth, but you can encompass them with a cheerful face and good character.',
                narrator: 'Abu Hurairah',
                collection: 'al-Mustadrak',
                reference: '191',
                topic: 'Good Character',
                reflection: 'You don\'t need money to win hearts — a warm smile and good manners go further.',
            },
            {
                id: 'ch7',
                arabicText: 'الْمُؤْمِنُ الَّذِي يُخَالِطُ النَّاسَ وَيَصْبِرُ عَلَى أَذَاهُمْ أَعْظَمُ أَجْرًا مِنَ الَّذِي لا يُخَالِطُ النَّاسَ وَلا يَصْبِرُ عَلَى أَذَاهُمْ',
                englishText: 'The believer who mixes with people and bears their annoyance with patience has a greater reward than the one who does not mix with them.',
                narrator: 'Abdullah ibn Umar',
                collection: 'Sunan Ibn Majah',
                reference: '4032',
                topic: 'Good Character',
                reflection: 'Withdrawing from people is easy — engaging patiently with them is the real test.',
            },
            {
                id: 'ch8',
                arabicText: 'مَا شَيْءٌ أَثْقَلُ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ مِنْ خُلُقٍ حَسَنٍ',
                englishText: 'Nothing is heavier on the believer\'s Scale on the Day of Resurrection than good character.',
                narrator: 'Abu ad-Darda',
                collection: 'Jami at-Tirmidhi',
                reference: '2002',
                topic: 'Good Character',
                reflection: 'On Judgment Day, your character outweighs even many acts of worship.',
            },
        ],
    },
    {
        id: 'patience',
        name: 'Patience & Trials',
        hadiths: [
            {
                id: 'p1',
                arabicText: 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ',
                englishText: 'How wonderful is the affair of the believer, for his affair is entirely good. If something good happens to him he is thankful, and that is good for him. If something bad happens to him he is patient, and that is good for him.',
                narrator: 'Suhaib ar-Rumi',
                collection: 'Sahih Muslim',
                reference: '2999',
                topic: 'Patience & Trials',
                reflection: 'A believer wins in every situation — gratitude in ease, patience in hardship.',
            },
            {
                id: 'p2',
                arabicText: 'إِنَّ عِظَمَ الْجَزَاءِ مَعَ عِظَمِ الْبَلاءِ',
                englishText: 'Indeed, the greatest reward comes with the greatest trial.',
                narrator: 'Anas ibn Malik',
                collection: 'Jami at-Tirmidhi',
                reference: '2396',
                topic: 'Patience & Trials',
                reflection: 'Your trial is proportional to your reward — the harder it is, the greater what awaits.',
            },
            {
                id: 'p3',
                arabicText: 'مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلا وَصَبٍ وَلا هَمٍّ وَلا حُزْنٍ وَلا أَذًى وَلا غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلا كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ',
                englishText: 'No fatigue, illness, anxiety, sorrow, harm, or sadness afflicts a Muslim — even the prick of a thorn — except that Allah expiates some of his sins thereby.',
                narrator: 'Abu Sa\'id al-Khudri',
                collection: 'Sahih al-Bukhari',
                reference: '5641',
                topic: 'Patience & Trials',
                reflection: 'Every hardship, no matter how small, is cleansing you of sins.',
            },
            {
                id: 'p4',
                arabicText: 'وَاعْلَمْ أَنَّ النَّصْرَ مَعَ الصَّبْرِ وَأَنَّ الْفَرَجَ مَعَ الْكَرْبِ وَأَنَّ مَعَ الْعُسْرِ يُسْرًا',
                englishText: 'Know that victory comes with patience, relief comes with affliction, and ease comes with hardship.',
                narrator: 'Abdullah ibn Abbas',
                collection: 'Musnad Ahmad',
                reference: '2800',
                topic: 'Patience & Trials',
                reflection: 'The darkest hour is just before dawn — relief is already on its way.',
            },
            {
                id: 'p5',
                arabicText: 'إِنَّ الصَّبْرَ عِنْدَ الصَّدْمَةِ الأُولَى',
                englishText: 'True patience is at the first stroke of calamity.',
                narrator: 'Anas ibn Malik',
                collection: 'Sahih al-Bukhari',
                reference: '1283',
                topic: 'Patience & Trials',
                reflection: 'Real strength shows in how you react in the first moment of hardship.',
            },
            {
                id: 'p6',
                arabicText: 'مَا أَعْطِيَ أَحَدٌ عَطَاءً خَيْرًا وَأَوْسَعَ مِنَ الصَّبْرِ',
                englishText: 'No one is given a gift better and more comprehensive than patience.',
                narrator: 'Abu Sa\'id al-Khudri',
                collection: 'Sahih al-Bukhari',
                reference: '1469',
                topic: 'Patience & Trials',
                reflection: 'Patience is the best gift you can receive — it turns every trial into growth.',
            },
            {
                id: 'p7',
                arabicText: 'إِنَّ اللَّهَ إِذَا أَحَبَّ قَوْمًا ابْتَلاهُمْ',
                englishText: 'When Allah loves a people, He tests them.',
                narrator: 'Anas ibn Malik',
                collection: 'Jami at-Tirmidhi',
                reference: '2396',
                topic: 'Patience & Trials',
                reflection: 'Being tested is a sign of Allah\'s love — the closer you are, the more you\'re refined.',
            },
            {
                id: 'p8',
                arabicText: 'يَوَدُّ أَهْلُ الْعَافِيَةِ يَوْمَ الْقِيَامَةِ حِينَ يُعْطَى أَهْلُ الْبَلاءِ الثَّوَابَ لَوْ أَنَّ جُلُودَهُمْ كَانَتْ قُرِضَتْ فِي الدُّنْيَا بِالْمَقَارِيضِ',
                englishText: 'On the Day of Resurrection, those who were healthy will wish their skins had been cut with scissors in this world, when they see the reward of those who were tested.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'Jami at-Tirmidhi',
                reference: '2402',
                topic: 'Patience & Trials',
                reflection: 'The reward for enduring trials is so immense that the comfortable will envy the patient.',
            },
        ],
    },
    {
        id: 'prayer',
        name: 'Prayer & Worship',
        hadiths: [
            {
                id: 'pr1',
                arabicText: 'أَقْرَبُ مَا يَكُونُ الْعَبْدُ مِنْ رَبِّهِ وَهُوَ سَاجِدٌ فَأَكْثِرُوا الدُّعَاءَ',
                englishText: 'The closest a servant is to his Lord is when he is in prostration, so increase your supplications.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '482',
                topic: 'Prayer & Worship',
                reflection: 'In sujood, you are at your closest to Allah — pour your heart out there.',
            },
            {
                id: 'pr2',
                arabicText: 'مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ',
                englishText: 'Whoever prays the two cool prayers (Fajr and Asr) will enter Paradise.',
                narrator: 'Abu Musa al-Ash\'ari',
                collection: 'Sahih al-Bukhari',
                reference: '574',
                topic: 'Prayer & Worship',
                reflection: 'Guard Fajr and Asr especially — these two carry Paradise\'s promise.',
            },
            {
                id: 'pr3',
                arabicText: 'أَرَأَيْتُمْ لَوْ أَنَّ نَهْرًا بِبَابِ أَحَدِكُمْ يَغْتَسِلُ مِنْهُ كُلَّ يَوْمٍ خَمْسَ مَرَّاتٍ هَلْ يَبْقَى مِنْ دَرَنِهِ شَيْءٌ',
                englishText: 'If there was a river at the door of one of you and he bathed in it five times a day, would any dirt remain on him? That is the example of the five daily prayers — Allah wipes away sins with them.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '528',
                topic: 'Prayer & Worship',
                reflection: 'Five prayers = five spiritual showers. Every salah washes away sins.',
            },
            {
                id: 'pr4',
                arabicText: 'الدُّعَاءُ هُوَ الْعِبَادَةُ',
                englishText: 'Supplication (du\'a) is the essence of worship.',
                narrator: 'An-Nu\'man ibn Bashir',
                collection: 'Jami at-Tirmidhi',
                reference: '3372',
                topic: 'Prayer & Worship',
                reflection: 'Simply asking Allah is itself an act of worship — never stop making du\'a.',
            },
            {
                id: 'pr5',
                arabicText: 'بَيْنَ الرَّجُلِ وَبَيْنَ الْكُفْرِ وَالشِّرْكِ تَرْكُ الصَّلاةِ',
                englishText: 'Between a person and disbelief and polytheism is the abandonment of prayer.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'Sahih Muslim',
                reference: '82',
                topic: 'Prayer & Worship',
                reflection: 'Prayer is the line between faith and its absence — never let it go.',
            },
            {
                id: 'pr6',
                arabicText: 'أَوَّلُ مَا يُحَاسَبُ بِهِ الْعَبْدُ يَوْمَ الْقِيَامَةِ الصَّلاةُ',
                englishText: 'The first thing a servant will be held accountable for on the Day of Judgment is prayer.',
                narrator: 'Abu Hurairah',
                collection: 'Sunan an-Nasa\'i',
                reference: '465',
                topic: 'Prayer & Worship',
                reflection: 'Your prayer record will be examined first — make sure it\'s the strongest part of your portfolio.',
            },
            {
                id: 'pr7',
                arabicText: 'مَنْ حَافَظَ عَلَى أَرْبَعِ رَكَعَاتٍ قَبْلَ الظُّهْرِ وَأَرْبَعٍ بَعْدَهَا حَرَّمَهُ اللَّهُ عَلَى النَّارِ',
                englishText: 'Whoever consistently prays four rak\'ahs before Dhuhr and four after it, Allah will make the Fire forbidden for him.',
                narrator: 'Umm Habibah',
                collection: 'Sunan an-Nasa\'i',
                reference: '1814',
                topic: 'Prayer & Worship',
                reflection: 'Sunnah prayers around Dhuhr are a shield from the Fire — a small investment, enormous return.',
            },
            {
                id: 'pr8',
                arabicText: 'صَلاةُ الْجَمَاعَةِ تَفْضُلُ صَلاةَ الْفَذِّ بِسَبْعٍ وَعِشْرِينَ دَرَجَةً',
                englishText: 'Prayer in congregation is twenty-seven times better than prayer offered individually.',
                narrator: 'Abdullah ibn Umar',
                collection: 'Sahih al-Bukhari',
                reference: '645',
                topic: 'Prayer & Worship',
                reflection: 'Praying together multiplies your reward 27x — community worship has immense barakah.',
            },
        ],
    },
    {
        id: 'knowledge',
        name: 'Knowledge & Learning',
        hadiths: [
            {
                id: 'kn1',
                arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
                englishText: 'Whoever takes a path seeking knowledge, Allah will make easy for him a path to Paradise.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2699',
                topic: 'Knowledge & Learning',
                reflection: 'Every bit of learning is a step toward Paradise — never stop seeking knowledge.',
            },
            {
                id: 'kn2',
                arabicText: 'بَلِّغُوا عَنِّي وَلَوْ آيَةً',
                englishText: 'Convey from me, even if it is a single verse.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sahih al-Bukhari',
                reference: '3461',
                topic: 'Knowledge & Learning',
                reflection: 'You don\'t need to be a scholar — share even one thing you know.',
            },
            {
                id: 'kn3',
                arabicText: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
                englishText: 'The best of you are those who learn the Quran and teach it.',
                narrator: 'Uthman ibn Affan',
                collection: 'Sahih al-Bukhari',
                reference: '5027',
                topic: 'Knowledge & Learning',
                reflection: 'Learning the Quran elevates you — teaching it makes you among the best of people.',
            },
            {
                id: 'kn4',
                arabicText: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
                englishText: 'Seeking knowledge is an obligation upon every Muslim.',
                narrator: 'Anas ibn Malik',
                collection: 'Sunan Ibn Majah',
                reference: '224',
                topic: 'Knowledge & Learning',
                reflection: 'Knowledge is not optional — it is as obligatory as prayer and fasting.',
            },
            {
                id: 'kn5',
                arabicText: 'إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلا مِنْ ثَلاثَةٍ إِلا مِنْ صَدَقَةٍ جَارِيَةٍ أَوْ عِلْمٍ يُنْتَفَعُ بِهِ أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ',
                englishText: 'When a person dies, his deeds come to an end except three: ongoing charity, knowledge that benefits, or a righteous child who prays for him.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '1631',
                topic: 'Knowledge & Learning',
                reflection: 'Beneficial knowledge is one of only three things that outlive you — invest in what lasts.',
            },
            {
                id: 'kn6',
                arabicText: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ',
                englishText: 'When Allah wills good for someone, He grants him understanding of the religion.',
                narrator: 'Mu\'awiyah',
                collection: 'Sahih al-Bukhari',
                reference: '71',
                topic: 'Knowledge & Learning',
                reflection: 'Deep religious understanding is a sign of Allah\'s special favor — pursue it.',
            },
            {
                id: 'kn7',
                arabicText: 'فَضْلُ الْعَالِمِ عَلَى الْعَابِدِ كَفَضْلِ الْقَمَرِ عَلَى سَائِرِ الْكَوَاكِبِ',
                englishText: 'The superiority of the scholar over the worshipper is like the superiority of the moon over all other stars.',
                narrator: 'Abu ad-Darda',
                collection: 'Sunan Abu Dawud',
                reference: '3641',
                topic: 'Knowledge & Learning',
                reflection: 'Knowledge illuminates like the moon — it guides not just you, but everyone around you.',
            },
            {
                id: 'kn8',
                arabicText: 'لا حَسَدَ إِلا فِي اثْنَتَيْنِ رَجُلٌ آتَاهُ اللَّهُ مَالا فَسَلَّطَهُ عَلَى هَلَكَتِهِ فِي الْحَقِّ وَرَجُلٌ آتَاهُ اللَّهُ الْحِكْمَةَ فَهُوَ يَقْضِي بِهَا وَيُعَلِّمُهَا',
                englishText: 'There is no envy except in two cases: a man whom Allah has given wealth and he spends it in the right way, and a man whom Allah has given wisdom and he judges by it and teaches it.',
                narrator: 'Abdullah ibn Mas\'ud',
                collection: 'Sahih al-Bukhari',
                reference: '73',
                topic: 'Knowledge & Learning',
                reflection: 'The only healthy ambition is wanting to give more and know more — not to have more.',
            },
        ],
    },
    {
        id: 'gratitude',
        name: 'Gratitude & Contentment',
        hadiths: [
            {
                id: 'g1',
                arabicText: 'انْظُرُوا إِلَى مَنْ أَسْفَلَ مِنْكُمْ وَلا تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ فَهُوَ أَجْدَرُ أَنْ لا تَزْدَرُوا نِعْمَةَ اللَّهِ',
                englishText: 'Look at those below you and do not look at those above you, for it is the best way to not belittle the blessings of Allah.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2963',
                topic: 'Gratitude & Contentment',
                reflection: 'Contentment comes from looking at those with less, not those with more.',
            },
            {
                id: 'g2',
                arabicText: 'مَنْ لا يَشْكُرِ النَّاسَ لا يَشْكُرِ اللَّهَ',
                englishText: 'Whoever does not thank people has not thanked Allah.',
                narrator: 'Abu Hurairah',
                collection: 'Jami at-Tirmidhi',
                reference: '1954',
                topic: 'Gratitude & Contentment',
                reflection: 'Gratitude to Allah starts with gratitude to the people in your life.',
            },
            {
                id: 'g3',
                arabicText: 'لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ',
                englishText: 'Richness is not having many possessions, but richness is the richness of the soul.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6446',
                topic: 'Gratitude & Contentment',
                reflection: 'True wealth isn\'t in your bank account — it\'s in being content with what you have.',
            },
            {
                id: 'g4',
                arabicText: 'ازْهَدْ فِي الدُّنْيَا يُحِبَّكَ اللَّهُ وَازْهَدْ فِيمَا عِنْدَ النَّاسِ يُحِبَّكَ النَّاسُ',
                englishText: 'Be detached from the world and Allah will love you. Be detached from what people have and people will love you.',
                narrator: 'Sahl ibn Sa\'d',
                collection: 'Sunan Ibn Majah',
                reference: '4102',
                topic: 'Gratitude & Contentment',
                reflection: 'Detachment from materialism wins you both divine love and human admiration.',
            },
            {
                id: 'g5',
                arabicText: 'مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سَرْبِهِ مُعَافًى فِي جَسَدِهِ عِنْدَهُ قُوتُ يَوْمِهِ فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا',
                englishText: 'Whoever among you wakes up secure in his dwelling, healthy in body, with food for the day — it is as if the whole world has been gathered for him.',
                narrator: 'Ubaidullah ibn Mihsan',
                collection: 'Jami at-Tirmidhi',
                reference: '2346',
                topic: 'Gratitude & Contentment',
                reflection: 'Safety, health, and food for today — if you have these three, you have everything.',
            },
            {
                id: 'g6',
                arabicText: 'الطَّاعِمُ الشَّاكِرُ بِمَنْزِلَةِ الصَّائِمِ الصَّابِرِ',
                englishText: 'The one who eats and is grateful is equal in reward to the one who fasts and is patient.',
                narrator: 'Abu Hurairah',
                collection: 'Jami at-Tirmidhi',
                reference: '2486',
                topic: 'Gratitude & Contentment',
                reflection: 'Gratitude after a meal can equal the reward of fasting — never underestimate thankfulness.',
            },
            {
                id: 'g7',
                arabicText: 'إِنَّ اللَّهَ لَيَرْضَى عَنِ الْعَبْدِ أَنْ يَأْكُلَ الأَكْلَةَ فَيَحْمَدَهُ عَلَيْهَا أَوْ يَشْرَبَ الشَّرْبَةَ فَيَحْمَدَهُ عَلَيْهَا',
                englishText: 'Allah is pleased with a servant who eats a meal and praises Him for it, or drinks a drink and praises Him for it.',
                narrator: 'Anas ibn Malik',
                collection: 'Sahih Muslim',
                reference: '2734',
                topic: 'Gratitude & Contentment',
                reflection: 'A simple "Alhamdulillah" after eating or drinking pleases your Lord — gratitude is effortless worship.',
            },
            {
                id: 'g8',
                arabicText: 'قَدْ أَفْلَحَ مَنْ أَسْلَمَ وَرُزِقَ كَفَافًا وَقَنَّعَهُ اللَّهُ بِمَا آتَاهُ',
                englishText: 'Successful is the one who embraces Islam, is given sufficient provision, and is made content by Allah with what he has.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sahih Muslim',
                reference: '1054',
                topic: 'Gratitude & Contentment',
                reflection: 'True success is Islam, enough to live on, and a content heart — not excess.',
            },
        ],
    },
    {
        id: 'actions',
        name: 'Deeds & Intentions',
        hadiths: [
            {
                id: 'a1',
                arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
                englishText: 'Actions are judged by intentions, and every person will get what they intended.',
                narrator: 'Umar ibn al-Khattab',
                collection: 'Sahih al-Bukhari',
                reference: '1',
                topic: 'Deeds & Intentions',
                reflection: 'Before any action, check your intention — it\'s what Allah judges you by.',
            },
            {
                id: 'a2',
                arabicText: 'أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
                englishText: 'The most beloved deeds to Allah are the most consistent, even if they are small.',
                narrator: 'Aisha',
                collection: 'Sahih al-Bukhari',
                reference: '6464',
                topic: 'Deeds & Intentions',
                reflection: 'Small consistent acts beat grand occasional efforts — build daily habits.',
            },
            {
                id: 'a3',
                arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
                englishText: 'Whoever believes in Allah and the Last Day should speak good or remain silent.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6018',
                topic: 'Deeds & Intentions',
                reflection: 'Words have weight — if it\'s not good, don\'t say it.',
            },
            {
                id: 'a4',
                arabicText: 'إِنَّ اللَّهَ لا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
                englishText: 'Allah does not look at your appearance or wealth, but He looks at your hearts and your deeds.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2564',
                topic: 'Deeds & Intentions',
                reflection: 'What matters to Allah is the state of your heart and the quality of your actions.',
            },
            {
                id: 'a5',
                arabicText: 'كُلُّ مَعْرُوفٍ صَدَقَةٌ',
                englishText: 'Every good deed is charity.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'Sahih al-Bukhari',
                reference: '6021',
                topic: 'Deeds & Intentions',
                reflection: 'Charity isn\'t just money — every good deed, no matter how small, counts.',
            },
            {
                id: 'a6',
                arabicText: 'لا تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئًا وَلَوْ أَنْ تَلْقَى أَخَاكَ بِوَجْهٍ طَلْقٍ',
                englishText: 'Do not belittle any good deed, even if it is meeting your brother with a cheerful face.',
                narrator: 'Abu Dharr',
                collection: 'Sahih Muslim',
                reference: '2626',
                topic: 'Deeds & Intentions',
                reflection: 'No good deed is too small — even your facial expression can be an act of worship.',
            },
            {
                id: 'a7',
                arabicText: 'دَعْ مَا يَرِيبُكَ إِلَى مَا لا يَرِيبُكَ',
                englishText: 'Leave what makes you doubtful for what does not make you doubtful.',
                narrator: 'al-Hasan ibn Ali',
                collection: 'Jami at-Tirmidhi',
                reference: '2518',
                topic: 'Deeds & Intentions',
                reflection: 'When in doubt, choose the safe path — certainty brings peace of mind.',
            },
            {
                id: 'a8',
                arabicText: 'الْحَلالُ بَيِّنٌ وَالْحَرَامُ بَيِّنٌ وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ',
                englishText: 'The lawful is clear and the unlawful is clear, and between them are doubtful matters.',
                narrator: 'An-Nu\'man ibn Bashir',
                collection: 'Sahih al-Bukhari',
                reference: '52',
                topic: 'Deeds & Intentions',
                reflection: 'Stay away from grey areas — the one who avoids doubtful matters protects his faith.',
            },
        ],
    },
    {
        id: 'family',
        name: 'Family & Relationships',
        hadiths: [
            {
                id: 'f1',
                arabicText: 'خَيْرُكُمْ خَيْرُكُمْ لأَهْلِهِ وَأَنَا خَيْرُكُمْ لأَهْلِي',
                englishText: 'The best of you are those who are best to their families, and I am the best of you to my family.',
                narrator: 'Aisha',
                collection: 'Jami at-Tirmidhi',
                reference: '3895',
                topic: 'Family & Relationships',
                reflection: 'Your treatment of your family is the truest measure of your character.',
            },
            {
                id: 'f2',
                arabicText: 'مَنْ سَرَّهُ أَنْ يُبْسَطَ لَهُ فِي رِزْقِهِ وَيُنْسَأَ لَهُ فِي أَثَرِهِ فَلْيَصِلْ رَحِمَهُ',
                englishText: 'Whoever would like his provision to be increased and his lifespan extended, let him maintain ties of kinship.',
                narrator: 'Anas ibn Malik',
                collection: 'Sahih al-Bukhari',
                reference: '5986',
                topic: 'Family & Relationships',
                reflection: 'Maintaining family ties is a direct cause of increased blessings in life.',
            },
            {
                id: 'f3',
                arabicText: 'رَغِمَ أَنْفُ ثُمَّ رَغِمَ أَنْفُ ثُمَّ رَغِمَ أَنْفُ مَنْ أَدْرَكَ أَبَوَيْهِ عِنْدَ الْكِبَرِ أَحَدَهُمَا أَوْ كِلاهُمَا فَلَمْ يَدْخُلِ الْجَنَّةَ',
                englishText: 'Disgraced is the one who finds his parents in old age, one or both of them, and does not enter Paradise through serving them.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2551',
                topic: 'Family & Relationships',
                reflection: 'Serving your parents in their old age is one of the surest paths to Paradise.',
            },
            {
                id: 'f4',
                arabicText: 'لَيْسَ الْوَاصِلُ بِالْمُكَافِئِ وَلَكِنِ الْوَاصِلُ الَّذِي إِذَا قُطِعَتْ رَحِمُهُ وَصَلَهَا',
                englishText: 'The one who truly maintains family ties is not the one who reciprocates — it is the one who maintains them even when they are cut off.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sahih al-Bukhari',
                reference: '5991',
                topic: 'Family & Relationships',
                reflection: 'True kinship means reaching out even when the other side doesn\'t.',
            },
            {
                id: 'f5',
                arabicText: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الأُمَّهَاتِ',
                englishText: 'Paradise lies at the feet of mothers.',
                narrator: 'Anas ibn Malik',
                collection: 'Sunan an-Nasa\'i',
                reference: '3104',
                topic: 'Family & Relationships',
                reflection: 'Your mother is your most direct path to Paradise — serve her with everything you have.',
            },
            {
                id: 'f6',
                arabicText: 'أَنْتَ وَمَالُكَ لأَبِيكَ',
                englishText: 'You and your wealth belong to your father.',
                narrator: 'Jabir ibn Abdullah',
                collection: 'Sunan Ibn Majah',
                reference: '2291',
                topic: 'Family & Relationships',
                reflection: 'Everything you have is partly owed to your parents — honor them with your resources.',
            },
            {
                id: 'f7',
                arabicText: 'مَنْ كَانَ لَهُ ثَلاثُ بَنَاتٍ فَصَبَرَ عَلَيْهِنَّ وَأَطْعَمَهُنَّ وَسَقَاهُنَّ وَكَسَاهُنَّ مِنْ جِدَتِهِ كُنَّ لَهُ حِجَابًا مِنَ النَّارِ يَوْمَ الْقِيَامَةِ',
                englishText: 'Whoever has three daughters and is patient with them, feeds them, gives them drink, and clothes them — they will be a shield for him against the Fire on the Day of Resurrection.',
                narrator: 'Uqbah ibn Amir',
                collection: 'Sunan Ibn Majah',
                reference: '3669',
                topic: 'Family & Relationships',
                reflection: 'Raising daughters well is a guaranteed shield from the Fire — what a noble investment.',
            },
            {
                id: 'f8',
                arabicText: 'كَفَى بِالْمَرْءِ إِثْمًا أَنْ يُضَيِّعَ مَنْ يَقُوتُ',
                englishText: 'It is sufficient sin for a person to neglect those he is responsible for feeding.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sunan Abu Dawud',
                reference: '1692',
                topic: 'Family & Relationships',
                reflection: 'Providing for your family is not just duty — neglecting them is a sin.',
            },
        ],
    },
    {
        id: 'tongue',
        name: 'Guarding the Tongue',
        hadiths: [
            {
                id: 't1',
                arabicText: 'مَنْ يَضْمَنْ لِي مَا بَيْنَ لَحْيَيْهِ وَمَا بَيْنَ رِجْلَيْهِ أَضْمَنْ لَهُ الْجَنَّةَ',
                englishText: 'Whoever guarantees me what is between his jaws (tongue) and what is between his legs, I guarantee him Paradise.',
                narrator: 'Sahl ibn Sa\'d',
                collection: 'Sahih al-Bukhari',
                reference: '6474',
                topic: 'Guarding the Tongue',
                reflection: 'Guard your tongue and your desires — these two determine your destination.',
            },
            {
                id: 't2',
                arabicText: 'إِنَّ الْعَبْدَ لَيَتَكَلَّمُ بِالْكَلِمَةِ مَا يَتَبَيَّنُ فِيهَا يَزِلُّ بِهَا فِي النَّارِ أَبْعَدَ مِمَّا بَيْنَ الْمَشْرِقِ',
                englishText: 'A servant may speak a word thoughtlessly that causes him to fall into the Hellfire deeper than the distance between east and west.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6477',
                topic: 'Guarding the Tongue',
                reflection: 'One careless word can destroy — think before you speak.',
            },
            {
                id: 't3',
                arabicText: 'لا يَسْتُرُ عَبْدٌ عَبْدًا فِي الدُّنْيَا إِلا سَتَرَهُ اللَّهُ يَوْمَ الْقِيَامَةِ',
                englishText: 'No servant conceals the faults of another servant in this world except that Allah will conceal his faults on the Day of Resurrection.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2590',
                topic: 'Guarding the Tongue',
                reflection: 'Cover others\' faults and Allah will cover yours — resist the urge to gossip.',
            },
            {
                id: 't4',
                arabicText: 'أَتَدْرُونَ مَا الْغِيبَةُ؟ ذِكْرُكَ أَخَاكَ بِمَا يَكْرَهُ',
                englishText: 'Do you know what backbiting is? It is mentioning your brother in a way he would dislike.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2589',
                topic: 'Guarding the Tongue',
                reflection: 'Even if it\'s true, speaking about someone in a way they\'d hate is backbiting.',
            },
            {
                id: 't5',
                arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ',
                englishText: 'Whoever believes in Allah and the Last Day, let him honor his guest.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6018',
                topic: 'Guarding the Tongue',
                reflection: 'True faith manifests in how you treat your guests — generosity is a sign of belief.',
            },
            {
                id: 't6',
                arabicText: 'لا يَدْخُلُ الْجَنَّةَ نَمَّامٌ',
                englishText: 'The one who carries tales (to cause mischief between people) will not enter Paradise.',
                narrator: 'Hudhaifah',
                collection: 'Sahih Muslim',
                reference: '105',
                topic: 'Guarding the Tongue',
                reflection: 'Carrying gossip and stirring conflict between people is a Paradise-depriving sin.',
            },
            {
                id: 't7',
                arabicText: 'إِنَّ الْعَبْدَ لَيَتَكَلَّمُ بِالْكَلِمَةِ مِنْ رِضْوَانِ اللَّهِ لا يُلْقِي لَهَا بَالا يَرْفَعُهُ اللَّهُ بِهَا دَرَجَاتٍ',
                englishText: 'A servant may speak a word pleasing to Allah that he does not consider significant, but Allah raises him ranks because of it.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6478',
                topic: 'Guarding the Tongue',
                reflection: 'A single good word can elevate your rank with Allah — speak with intention.',
            },
        ],
    },
    {
        id: 'remembrance',
        name: 'Remembrance of Allah',
        hadiths: [
            {
                id: 'r1',
                arabicText: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ ثَقِيلَتَانِ فِي الْمِيزَانِ حَبِيبَتَانِ إِلَى الرَّحْمَنِ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ',
                englishText: 'Two phrases are light on the tongue, heavy on the Scale, and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil Azeem.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6406',
                topic: 'Remembrance of Allah',
                reflection: 'These two phrases take seconds to say but weigh heavily on your Scale of deeds.',
            },
            {
                id: 'r2',
                arabicText: 'أَقْرَبُ مَا يَكُونُ الرَّبُّ مِنَ الْعَبْدِ فِي جَوْفِ اللَّيْلِ الآخِرِ',
                englishText: 'The closest the Lord is to His servant is in the last part of the night.',
                narrator: 'Amr ibn Absah',
                collection: 'Jami at-Tirmidhi',
                reference: '3579',
                topic: 'Remembrance of Allah',
                reflection: 'The last third of the night is golden — wake up and talk to Allah.',
            },
            {
                id: 'r3',
                arabicText: 'مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لا يَذْكُرُ رَبَّهُ مَثَلُ الْحَيِّ وَالْمَيِّتِ',
                englishText: 'The example of one who remembers his Lord and one who does not is like the example of the living and the dead.',
                narrator: 'Abu Musa al-Ash\'ari',
                collection: 'Sahih al-Bukhari',
                reference: '6407',
                topic: 'Remembrance of Allah',
                reflection: 'Dhikr is the difference between a spiritually alive heart and a dead one.',
            },
            {
                id: 'r4',
                arabicText: 'يَقُولُ اللَّهُ تَعَالَى أَنَا عِنْدَ ظَنِّ عَبْدِي بِي',
                englishText: 'Allah says: I am as My servant thinks of Me.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '7405',
                topic: 'Remembrance of Allah',
                reflection: 'Think well of Allah — your expectation of Him shapes His response to you.',
            },
            {
                id: 'r5',
                arabicText: 'مَنْ قَالَ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ حُطَّتْ خَطَايَاهُ وَإِنْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ',
                englishText: 'Whoever says SubhanAllahi wa bihamdihi one hundred times a day, his sins will be forgiven even if they are like the foam of the sea.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6405',
                topic: 'Remembrance of Allah',
                reflection: '100 times a day — takes 5 minutes, erases a sea of sins.',
            },
            {
                id: 'r6',
                arabicText: 'لا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ كَنْزٌ مِنْ كُنُوزِ الْجَنَّةِ',
                englishText: 'La hawla wa la quwwata illa billah is a treasure from the treasures of Paradise.',
                narrator: 'Abu Musa al-Ash\'ari',
                collection: 'Sahih al-Bukhari',
                reference: '6384',
                topic: 'Remembrance of Allah',
                reflection: 'This phrase is a treasure you can claim right now — say it and earn Paradise\'s riches.',
            },
            {
                id: 'r7',
                arabicText: 'أَلا أُنَبِّئُكُمْ بِخَيْرِ أَعْمَالِكُمْ وَأَزْكَاهَا عِنْدَ مَلِيكِكُمْ؟ ذِكْرُ اللَّهِ',
                englishText: 'Shall I not tell you the best of your deeds, the purest of them with your King? The remembrance of Allah.',
                narrator: 'Abu ad-Darda',
                collection: 'Jami at-Tirmidhi',
                reference: '3377',
                topic: 'Remembrance of Allah',
                reflection: 'Dhikr outranks all other deeds — it\'s the most beloved action you can do.',
            },
            {
                id: 'r8',
                arabicText: 'أَحَبُّ الْكَلامِ إِلَى اللَّهِ أَرْبَعٌ سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلا إِلَهَ إِلا اللَّهُ وَاللَّهُ أَكْبَرُ',
                englishText: 'The most beloved words to Allah are four: SubhanAllah, Alhamdulillah, La ilaha illa Allah, and Allahu Akbar.',
                narrator: 'Samurah ibn Jundub',
                collection: 'Sahih Muslim',
                reference: '2137',
                topic: 'Remembrance of Allah',
                reflection: 'Four phrases, beloved to Allah — make them your constant companions throughout the day.',
            },
        ],
    },
    {
        id: 'brotherhood',
        name: 'Brotherhood & Community',
        hadiths: [
            {
                id: 'b1',
                arabicText: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ لا يَظْلِمُهُ وَلا يُسْلِمُهُ',
                englishText: 'A Muslim is the brother of a Muslim — he does not wrong him nor does he abandon him.',
                narrator: 'Abdullah ibn Umar',
                collection: 'Sahih al-Bukhari',
                reference: '2442',
                topic: 'Brotherhood & Community',
                reflection: 'Stand by your community — don\'t wrong them or leave them when they need you.',
            },
            {
                id: 'b2',
                arabicText: 'مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى',
                englishText: 'The believers in their mutual love, mercy, and compassion are like one body — if one limb complains, the rest of the body responds with sleeplessness and fever.',
                narrator: 'An-Nu\'man ibn Bashir',
                collection: 'Sahih Muslim',
                reference: '2586',
                topic: 'Brotherhood & Community',
                reflection: 'When one Muslim suffers, the whole community should feel it and respond.',
            },
            {
                id: 'b3',
                arabicText: 'لا تَحَاسَدُوا وَلا تَنَاجَشُوا وَلا تَبَاغَضُوا وَلا تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا',
                englishText: 'Do not envy one another, do not inflate prices, do not hate one another, do not turn away from one another — be servants of Allah, brothers.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2564',
                topic: 'Brotherhood & Community',
                reflection: 'Brotherhood requires actively removing jealousy, hatred, and competition from your heart.',
            },
            {
                id: 'b4',
                arabicText: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
                englishText: 'A Muslim is one from whose tongue and hand other Muslims are safe.',
                narrator: 'Abdullah ibn Amr',
                collection: 'Sahih al-Bukhari',
                reference: '10',
                topic: 'Brotherhood & Community',
                reflection: 'Your Islam is proven by how safe others feel around you — in speech and in action.',
            },
            {
                id: 'b5',
                arabicText: 'لا يَحِلُّ لِمُسْلِمٍ أَنْ يَهْجُرَ أَخَاهُ فَوْقَ ثَلاثِ لَيَالٍ',
                englishText: 'It is not permissible for a Muslim to shun his brother for more than three nights.',
                narrator: 'Abu Ayyub al-Ansari',
                collection: 'Sahih al-Bukhari',
                reference: '6077',
                topic: 'Brotherhood & Community',
                reflection: 'Holding grudges beyond three days is impermissible — reach out and reconcile.',
            },
            {
                id: 'b6',
                arabicText: 'مَنْ عَادَ مَرِيضًا لَمْ يَزَلْ فِي خُرْفَةِ الْجَنَّةِ حَتَّى يَرْجِعَ',
                englishText: 'Whoever visits a sick person continues to be in the harvest of Paradise until he returns.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2568',
                topic: 'Brotherhood & Community',
                reflection: 'Visiting the sick isn\'t just kind — you\'re literally harvesting Paradise rewards the entire time.',
            },
            {
                id: 'b7',
                arabicText: 'وَاللَّهِ لا يُؤْمِنُ وَاللَّهِ لا يُؤْمِنُ وَاللَّهِ لا يُؤْمِنُ الَّذِي لا يَأْمَنُ جَارُهُ بَوَائِقَهُ',
                englishText: 'By Allah, he does not believe! By Allah, he does not believe! By Allah, he does not believe! — the one whose neighbor does not feel safe from his harm.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih al-Bukhari',
                reference: '6016',
                topic: 'Brotherhood & Community',
                reflection: 'The Prophet ﷺ swore three times — your neighbor\'s safety from you is integral to your faith.',
            },
        ],
    },
    {
        id: 'forgiveness',
        name: 'Forgiveness & Repentance',
        hadiths: [
            {
                id: 'fg1',
                arabicText: 'وَالَّذِي نَفْسِي بِيَدِهِ لَوْ لَمْ تُذْنِبُوا لَذَهَبَ اللَّهُ بِكُمْ وَلَجَاءَ بِقَوْمٍ يُذْنِبُونَ فَيَسْتَغْفِرُونَ اللَّهَ فَيَغْفِرُ لَهُمْ',
                englishText: 'By the One in whose hand is my soul, if you did not sin, Allah would replace you with people who would sin and then seek His forgiveness, and He would forgive them.',
                narrator: 'Abu Hurairah',
                collection: 'Sahih Muslim',
                reference: '2749',
                topic: 'Forgiveness & Repentance',
                reflection: 'Allah loves to forgive — don\'t despair after sinning, turn back to Him.',
            },
            {
                id: 'fg2',
                arabicText: 'إِنَّ اللَّهَ يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ وَيَبْسُطُ يَدَهُ بِالنَّهَارِ لِيَتُوبَ مُسِيءُ اللَّيْلِ',
                englishText: 'Allah extends His Hand at night to accept the repentance of those who sinned during the day, and extends His Hand during the day to accept the repentance of those who sinned at night.',
                narrator: 'Abu Musa al-Ash\'ari',
                collection: 'Sahih Muslim',
                reference: '2759',
                topic: 'Forgiveness & Repentance',
                reflection: 'It\'s never too late — Allah\'s door of repentance is always open, day and night.',
            },
            {
                id: 'fg3',
                arabicText: 'كُلُّ ابْنِ آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ',
                englishText: 'Every son of Adam sins, and the best of sinners are those who constantly repent.',
                narrator: 'Anas ibn Malik',
                collection: 'Jami at-Tirmidhi',
                reference: '2499',
                topic: 'Forgiveness & Repentance',
                reflection: 'Perfection isn\'t being sinless — it\'s being quick to repent.',
            },
            {
                id: 'fg4',
                arabicText: 'يَا عِبَادِي إِنَّكُمْ تُخْطِئُونَ بِاللَّيْلِ وَالنَّهَارِ وَأَنَا أَغْفِرُ الذُّنُوبَ جَمِيعًا فَاسْتَغْفِرُونِي أَغْفِرْ لَكُمْ',
                englishText: 'O My servants, you sin by night and by day, and I forgive all sins, so seek My forgiveness and I will forgive you.',
                narrator: 'Abu Dharr',
                collection: 'Sahih Muslim',
                reference: '2577',
                topic: 'Forgiveness & Repentance',
                reflection: 'Allah\'s capacity to forgive is limitless — the only question is whether you ask.',
            },
            {
                id: 'fg5',
                arabicText: 'إِنَّ اللَّهَ يَقْبَلُ تَوْبَةَ الْعَبْدِ مَا لَمْ يُغَرْغِرْ',
                englishText: 'Allah accepts the repentance of His servant as long as the soul has not reached the throat.',
                narrator: 'Abdullah ibn Umar',
                collection: 'Jami at-Tirmidhi',
                reference: '3537',
                topic: 'Forgiveness & Repentance',
                reflection: 'Repentance is accepted until your final breath — it\'s never too late to turn back.',
            },
            {
                id: 'fg6',
                arabicText: 'التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لا ذَنْبَ لَهُ',
                englishText: 'The one who repents from sin is like one who has no sin.',
                narrator: 'Abdullah ibn Mas\'ud',
                collection: 'Sunan Ibn Majah',
                reference: '4250',
                topic: 'Forgiveness & Repentance',
                reflection: 'Sincere repentance erases sin completely — you get a clean slate.',
            },
            {
                id: 'fg7',
                arabicText: 'لَلَّهُ أَشَدُّ فَرَحًا بِتَوْبَةِ عَبْدِهِ مِنْ أَحَدِكُمْ سَقَطَ عَلَى بَعِيرِهِ وَقَدْ أَضَلَّهُ فِي أَرْضِ فَلاةٍ',
                englishText: 'Allah is more pleased with the repentance of His servant than one of you who finds his lost camel in a barren desert.',
                narrator: 'Anas ibn Malik',
                collection: 'Sahih Muslim',
                reference: '2747',
                topic: 'Forgiveness & Repentance',
                reflection: 'Imagine the joy of finding something precious you thought was lost forever — Allah feels even more joy when you repent.',
            },
        ],
    },
];

/** Get all hadiths as a flat array */
export function getAllCuratedHadiths(): CuratedHadith[] {
    return HADITH_TOPICS.flatMap(t => t.hadiths);
}
