import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { Note } from '../../features/notes/domain/Note';

/**
 * Format options for note exports.
 */
export type ExportFormat = 'text' | 'json' | 'markdown';

/**
 * Service for exporting user notes to various formats.
 */
export class ExportService {
    /**
     * Export notes and open the native share sheet.
     */
    static async exportNotes(
        notes: Note[],
        format: ExportFormat = 'text',
        surahNames?: Record<number, string>,
    ): Promise<void> {
        if (notes.length === 0) {
            throw new Error('No notes to export');
        }

        let content: string;
        let filename: string;
        let mimeType: string;

        switch (format) {
            case 'markdown':
                content = ExportService.toMarkdown(notes, surahNames);
                filename = `QuranNotes_Export_${ExportService.getDateStamp()}.md`;
                mimeType = 'text/markdown';
                break;
            case 'json':
                content = ExportService.toJSON(notes);
                filename = `QuranNotes_Export_${ExportService.getDateStamp()}.json`;
                mimeType = 'application/json';
                break;
            default:
                content = ExportService.toText(notes, surahNames);
                filename = `QuranNotes_Export_${ExportService.getDateStamp()}.txt`;
                mimeType = 'text/plain';
                break;
        }

        const file = new File(Paths.cache, filename);
        file.create();
        file.write(content);

        const isAvailable = await Sharing.isAvailableAsync();
        if (!isAvailable) {
            throw new Error('Sharing is not available on this device');
        }

        await Sharing.shareAsync(file.uri, {
            mimeType,
            dialogTitle: 'Export QuranNotes',
            UTI: format === 'json' ? 'public.json' : 'public.plain-text',
        });
    }

    // ── Formatters ───────────────────────────────────────────────────

    private static toText(notes: Note[], surahNames?: Record<number, string>): string {
        const header = `QuranNotes Export\n${'='.repeat(40)}\nExported: ${new Date().toLocaleDateString()}\nTotal Notes: ${notes.length}\n${'='.repeat(40)}\n\n`;

        const grouped = ExportService.groupBySurah(notes);
        let body = '';

        for (const [surahId, surahNotes] of Object.entries(grouped)) {
            const name = surahNames?.[Number(surahId)] || `Surah ${surahId}`;
            body += `─── ${name} ───\n\n`;

            for (const note of surahNotes) {
                const verse = note.verseId ? `Verse ${note.verseId}` : 'General';
                const date = new Date(note.updatedAt).toLocaleDateString();
                body += `[${verse}] (${date})\n${note.content}\n\n`;
            }

            body += '\n';
        }

        return header + body + `\n─── End of Export ───\nGenerated by QuranNotes`;
    }

    private static toMarkdown(notes: Note[], surahNames?: Record<number, string>): string {
        let md = `# QuranNotes Export\n\n`;
        md += `> Exported on ${new Date().toLocaleDateString()} · ${notes.length} notes\n\n---\n\n`;

        const grouped = ExportService.groupBySurah(notes);

        for (const [surahId, surahNotes] of Object.entries(grouped)) {
            const name = surahNames?.[Number(surahId)] || `Surah ${surahId}`;
            md += `## ${name}\n\n`;

            for (const note of surahNotes) {
                const verse = note.verseId ? `Verse ${note.verseId}` : 'General';
                const date = new Date(note.updatedAt).toLocaleDateString();
                md += `### ${verse}\n`;
                md += `*${date}*\n\n`;
                md += `${note.content}\n\n---\n\n`;
            }
        }

        md += `\n*Generated by QuranNotes*\n`;
        return md;
    }

    private static toJSON(notes: Note[]): string {
        const exportData = {
            appName: 'QuranNotes',
            exportDate: new Date().toISOString(),
            totalNotes: notes.length,
            notes: notes.map((n) => ({
                surahId: n.surahId,
                verseId: n.verseId || null,
                content: n.content,
                folderId: n.folderId || null,
                createdAt: n.createdAt,
                updatedAt: n.updatedAt,
            })),
        };

        return JSON.stringify(exportData, null, 2);
    }

    // ── Helpers ──────────────────────────────────────────────────────

    private static groupBySurah(notes: Note[]): Record<string, Note[]> {
        return notes.reduce(
            (acc, note) => {
                const key = String(note.surahId);
                if (!acc[key]) acc[key] = [];
                acc[key].push(note);
                return acc;
            },
            {} as Record<string, Note[]>,
        );
    }

    private static getDateStamp(): string {
        const d = new Date();
        return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
    }
}
