#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const TARGET = path.join(__dirname, '..', 'src', 'data', 'moodVerses.json');
const existing = JSON.parse(fs.readFileSync(TARGET, 'utf8'));

const newMoods = {
    seeking_guidance: [
        { s: 1, v: 6, a: "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ", t: "Guide us to the straight path.", th: "guidance" },
        { s: 17, v: 9, a: "إِنَّ هَـٰذَا ٱلْقُرْءَانَ يَهْدِى لِلَّتِى هِىَ أَقْوَمُ", t: "This Quran guides to that which is most suitable.", th: "quran" },
        { s: 2, v: 185, a: "هُدًى لِّلنَّاسِ وَبَيِّنَـٰتٍ مِّنَ ٱلْهُدَىٰ وَٱلْفُرْقَانِ", t: "Guidance for the people and clear proofs.", th: "quran" },
        { s: 29, v: 69, a: "وَٱلَّذِينَ جَـٰهَدُوا۟ فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", t: "Those who strive for Us — We will guide them.", th: "striving" },
        { s: 93, v: 7, a: "وَوَجَدَكَ ضَآلًّا فَهَدَىٰ", t: "He found you lost and guided you.", th: "guidance" },
        { s: 40, v: 60, a: "ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ", t: "Call upon Me; I will respond to you.", th: "dua" },
        { s: 2, v: 186, a: "فَإِنِّى قَرِيبٌ أُجِيبُ دَعْوَةَ ٱلدَّاعِ", t: "Indeed I am near. I respond to the supplicant.", th: "closeness" },
        { s: 3, v: 8, a: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا", t: "Our Lord, let not our hearts deviate after You guided us.", th: "dua" },
        { s: 64, v: 11, a: "وَمَن يُؤْمِنۢ بِٱللَّهِ يَهْدِ قَلْبَهُۥ", t: "Whoever believes in Allah — He will guide his heart.", th: "faith" },
        { s: 6, v: 161, a: "قُلْ إِنَّنِى هَدَىٰنِى رَبِّىٓ إِلَىٰ صِرَٰطٍ مُّسْتَقِيمٍ", t: "My Lord has guided me to a straight path.", th: "guidance" },
        { s: 76, v: 3, a: "إِنَّا هَدَيْنَـٰهُ ٱلسَّبِيلَ", t: "Indeed, We guided him to the way.", th: "guidance" },
        { s: 10, v: 57, a: "قَدْ جَآءَتْكُم مَّوْعِظَةٌ مِّن رَّبِّكُمْ وَشِفَآءٌ لِّمَا فِى ٱلصُّدُورِ", t: "An instruction from your Lord and healing for the breasts.", th: "healing" },
        { s: 24, v: 35, a: "ٱللَّهُ نُورُ ٱلسَّمَـٰوَاتِ وَٱلْأَرْضِ", t: "Allah is the Light of the heavens and the earth.", th: "light" },
        { s: 2, v: 257, a: "ٱللَّهُ وَلِىُّ ٱلَّذِينَ ءَامَنُوا۟ يُخْرِجُهُم مِّنَ ٱلظُّلُمَـٰتِ إِلَى ٱلنُّورِ", t: "Allah brings them out of darkness into light.", th: "salvation" },
        { s: 42, v: 52, a: "وَإِنَّكَ لَتَهْدِىٓ إِلَىٰ صِرَٰطٍ مُّسْتَقِيمٍ", t: "Indeed, you guide to a straight path.", th: "guidance" },
        { s: 2, v: 152, a: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ", t: "Remember Me; I will remember you.", th: "remembrance" },
        { s: 13, v: 28, a: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", t: "In the remembrance of Allah do hearts find rest.", th: "peace" },
        { s: 20, v: 25, a: "رَبِّ ٱشْرَحْ لِى صَدْرِى", t: "My Lord, expand for me my chest.", th: "dua" },
        { s: 20, v: 50, a: "رَبُّنَا ٱلَّذِىٓ أَعْطَىٰ كُلَّ شَىْءٍ خَلْقَهُۥ ثُمَّ هَدَىٰ", t: "Our Lord gave each thing its form and then guided it.", th: "purpose" },
        { s: 6, v: 122, a: "أَوَمَن كَانَ مَيْتًا فَأَحْيَيْنَـٰهُ وَجَعَلْنَا لَهُۥ نُورًا", t: "Is one who was dead and We gave him life and light?", th: "light" },
        { s: 39, v: 53, a: "لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ", t: "Do not despair of the mercy of Allah.", th: "mercy" },
        { s: 65, v: 2, a: "وَمَن يَتَّقِ ٱللَّهَ يَجْعَل لَّهُۥ مَخْرَجًا", t: "Whoever fears Allah — He will make for him a way out.", th: "tawakkul" },
        { s: 3, v: 173, a: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ", t: "Sufficient for us is Allah.", th: "trust" },
        { s: 25, v: 1, a: "تَبَارَكَ ٱلَّذِى نَزَّلَ ٱلْفُرْقَانَ", t: "Blessed is He who sent down the Criterion.", th: "quran" },
        { s: 2, v: 256, a: "قَد تَّبَيَّنَ ٱلرُّشْدُ مِنَ ٱلْغَىِّ", t: "The right course has become clear from the wrong.", th: "clarity" },
        { s: 27, v: 62, a: "أَمَّن يُجِيبُ ٱلْمُضْطَرَّ إِذَا دَعَاهُ", t: "Is He not the One who responds to the distressed?", th: "dua" },
        { s: 7, v: 56, a: "إِنَّ رَحْمَتَ ٱللَّهِ قَرِيبٌ", t: "The mercy of Allah is near.", th: "mercy" },
        { s: 33, v: 43, a: "لِيُخْرِجَكُم مِّنَ ٱلظُّلُمَـٰتِ إِلَى ٱلنُّورِ", t: "To bring you out of darkness into light.", th: "mercy" },
        { s: 14, v: 12, a: "وَقَدْ هَدَىٰنَا سُبُلَنَا", t: "He has guided us to our ways.", th: "guidance" },
        { s: 4, v: 175, a: "فَسَيُدْخِلُهُمْ فِى رَحْمَةٍ مِّنْهُ وَفَضْلٍ", t: "He will admit them to mercy and bounty from Him.", th: "mercy" },
        { s: 46, v: 15, a: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ", t: "My Lord, enable me to be grateful for Your favor.", th: "dua" },
        { s: 23, v: 118, a: "رَّبِّ ٱغْفِرْ وَٱرْحَمْ", t: "My Lord, forgive and have mercy.", th: "dua" },
        { s: 9, v: 51, a: "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا", t: "Nothing befalls us except what Allah has written.", th: "qadr" },
        { s: 20, v: 46, a: "لَا تَخَافَآ إِنَّنِى مَعَكُمَآ", t: "Fear not. Indeed, I am with you both.", th: "comfort" },
        { s: 21, v: 87, a: "لَّآ إِلَـٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ", t: "There is no deity except You; exalted are You.", th: "repentance" },
        { s: 73, v: 8, a: "وَٱذْكُرِ ٱسْمَ رَبِّكَ", t: "And remember the name of your Lord.", th: "devotion" },
        { s: 94, v: 5, a: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا", t: "Indeed, with hardship comes ease.", th: "hope" },
        { s: 3, v: 159, a: "فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى ٱللَّهِ", t: "When you have decided, rely upon Allah.", th: "trust" },
        { s: 12, v: 87, a: "لَا تَا۟يْـَٔسُوا۟ مِن رَّوْحِ ٱللَّهِ", t: "Do not despair of relief from Allah.", th: "hope" },
        { s: 39, v: 10, a: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", t: "The patient get their reward without account.", th: "reward" },
        { s: 8, v: 46, a: "وَٱصْبِرُوٓا۟ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ", t: "Be patient. Allah is with the patient.", th: "patience" },
        { s: 93, v: 3, a: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", t: "Your Lord has not taken leave of you.", th: "comfort" },
        { s: 93, v: 5, a: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰٓ", t: "Your Lord will give you, and you will be satisfied.", th: "promise" },
        { s: 11, v: 56, a: "إِنِّى تَوَكَّلْتُ عَلَى ٱللَّهِ", t: "Indeed, I have relied upon Allah.", th: "trust" },
        { s: 28, v: 56, a: "وَلَـٰكِنَّ ٱللَّهَ يَهْدِى مَن يَشَآءُ", t: "But Allah guides whom He wills.", th: "guidance" }
    ],
    at_peace: [
        { s: 13, v: 28, a: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", t: "In the remembrance of Allah do hearts find rest.", th: "peace" },
        { s: 89, v: 27, a: "يَـٰٓأَيَّتُهَا ٱلنَّفْسُ ٱلْمُطْمَئِنَّةُ", t: "O reassured soul.", th: "soul" },
        { s: 89, v: 28, a: "ٱرْجِعِىٓ إِلَىٰ رَبِّكِ رَاضِيَةً مَّرْضِيَّةً", t: "Return to your Lord, well-pleased and pleasing.", th: "return" },
        { s: 89, v: 30, a: "وَٱدْخُلِى جَنَّتِى", t: "And enter My Paradise.", th: "paradise" },
        { s: 2, v: 152, a: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ", t: "Remember Me; I will remember you.", th: "remembrance" },
        { s: 10, v: 62, a: "أَلَآ إِنَّ أَوْلِيَآءَ ٱللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", t: "The allies of Allah — no fear or grief for them.", th: "security" },
        { s: 48, v: 4, a: "هُوَ ٱلَّذِىٓ أَنزَلَ ٱلسَّكِينَةَ فِى قُلُوبِ ٱلْمُؤْمِنِينَ", t: "He sent down tranquility into the hearts of the believers.", th: "tranquility" },
        { s: 24, v: 35, a: "ٱللَّهُ نُورُ ٱلسَّمَـٰوَاتِ وَٱلْأَرْضِ", t: "Allah is the Light of the heavens and the earth.", th: "light" },
        { s: 30, v: 21, a: "وَمِنْ ءَايَـٰتِهِۦٓ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَٰجًا لِّتَسْكُنُوٓا۟ إِلَيْهَا", t: "He created for you spouses to find peace with them.", th: "love" },
        { s: 55, v: 60, a: "هَلْ جَزَآءُ ٱلْإِحْسَـٰنِ إِلَّا ٱلْإِحْسَـٰنُ", t: "Is the reward for good anything but good?", th: "reward" },
        { s: 16, v: 97, a: "فَلَنُحْيِيَنَّهُۥ حَيَوٰةً طَيِّبَةً", t: "We will cause them to live a good life.", th: "life" },
        { s: 14, v: 7, a: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", t: "If you are grateful, I will increase you.", th: "gratitude" },
        { s: 93, v: 5, a: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰٓ", t: "Your Lord will give you, and you will be satisfied.", th: "promise" },
        { s: 73, v: 8, a: "وَٱذْكُرِ ٱسْمَ رَبِّكَ وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا", t: "Remember the name of your Lord and devote yourself.", th: "devotion" },
        { s: 20, v: 14, a: "وَأَقِمِ ٱلصَّلَوٰةَ لِذِكْرِىٓ", t: "And establish prayer for My remembrance.", th: "prayer" },
        { s: 6, v: 162, a: "قُلْ إِنَّ صَلَاتِى وَنُسُكِى وَمَحْيَاىَ وَمَمَاتِى لِلَّهِ", t: "My prayer, my sacrifice, my living and dying are for Allah.", th: "devotion" },
        { s: 1, v: 2, a: "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ", t: "All praise is due to Allah, Lord of the worlds.", th: "praise" },
        { s: 55, v: 13, a: "فَبِأَىِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ", t: "Which of the favors of your Lord would you deny?", th: "blessings" },
        { s: 93, v: 11, a: "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ", t: "And as for the favor of your Lord, proclaim it.", th: "sharing" },
        { s: 3, v: 173, a: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ", t: "Sufficient for us is Allah.", th: "trust" },
        { s: 65, v: 3, a: "وَمَن يَتَوَكَّلْ عَلَى ٱللَّهِ فَهُوَ حَسْبُهُۥٓ", t: "Whoever relies upon Allah — He is sufficient.", th: "trust" },
        { s: 10, v: 58, a: "قُلْ بِفَضْلِ ٱللَّهِ وَبِرَحْمَتِهِۦ فَبِذَٰلِكَ فَلْيَفْرَحُوا۟", t: "In the bounty of Allah and His mercy — let them rejoice.", th: "joy" },
        { s: 40, v: 60, a: "ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ", t: "Call upon Me; I will respond.", th: "dua" },
        { s: 2, v: 186, a: "فَإِنِّى قَرِيبٌ", t: "Indeed I am near.", th: "closeness" },
        { s: 39, v: 75, a: "وَقِيلَ ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ", t: "Praise is due to Allah, Lord of the worlds.", th: "paradise" },
        { s: 56, v: 26, a: "سَلَـٰمًا سَلَـٰمًا", t: "Peace, peace.", th: "paradise" },
        { s: 36, v: 58, a: "سَلَـٰمٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ", t: "Peace — a word from a Merciful Lord.", th: "peace" },
        { s: 97, v: 5, a: "سَلَـٰمٌ هِىَ حَتَّىٰ مَطْلَعِ ٱلْفَجْرِ", t: "Peace it is until the emergence of dawn.", th: "peace" },
        { s: 25, v: 75, a: "أُو۟لَـٰٓئِكَ يُجْزَوْنَ ٱلْغُرْفَةَ بِمَا صَبَرُوا۟ وَيُلَقَّوْنَ فِيهَا تَحِيَّةً وَسَلَـٰمًا", t: "They will be rewarded the upper chambers for their patience, and met with greetings and peace.", th: "reward" },
        { s: 7, v: 56, a: "إِنَّ رَحْمَتَ ٱللَّهِ قَرِيبٌ", t: "The mercy of Allah is near.", th: "mercy" },
        { s: 93, v: 3, a: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", t: "Your Lord has not taken leave of you.", th: "comfort" },
        { s: 94, v: 5, a: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا", t: "With hardship comes ease.", th: "hope" },
        { s: 17, v: 70, a: "وَلَقَدْ كَرَّمْنَا بَنِىٓ ءَادَمَ", t: "We have honored the children of Adam.", th: "honor" },
        { s: 45, v: 13, a: "وَسَخَّرَ لَكُم مَّا فِى ٱلسَّمَـٰوَاتِ وَمَا فِى ٱلْأَرْضِ جَمِيعًا مِّنْهُ", t: "He subjected to you all that is in the heavens and earth.", th: "bounty" },
        { s: 16, v: 18, a: "وَإِن تَعُدُّوا۟ نِعْمَةَ ٱللَّهِ لَا تُحْصُوهَا", t: "If you count Allah's favors, you could not enumerate them.", th: "blessings" },
        { s: 35, v: 3, a: "يَـٰٓأَيُّهَا ٱلنَّاسُ ٱذْكُرُوا۟ نِعْمَتَ ٱللَّهِ عَلَيْكُمْ", t: "O mankind, remember the favor of Allah upon you.", th: "remembrance" },
        { s: 25, v: 48, a: "وَهُوَ ٱلَّذِىٓ أَرْسَلَ ٱلرِّيَـٰحَ بُشْرًۢا بَيْنَ يَدَىْ رَحْمَتِهِۦ", t: "He sends the winds as good tidings before His mercy.", th: "nature" },
        { s: 28, v: 73, a: "وَمِن رَّحْمَتِهِۦ جَعَلَ لَكُمُ ٱلَّيْلَ وَٱلنَّهَارَ", t: "Out of His mercy He made for you night and day.", th: "mercy" },
        { s: 59, v: 23, a: "هُوَ ٱللَّهُ ٱلَّذِى لَآ إِلَـٰهَ إِلَّا هُوَ ٱلْمَلِكُ ٱلْقُدُّوسُ ٱلسَّلَـٰمُ", t: "He is Allah — the King, the Pure, the Perfection of Peace.", th: "names" },
        { s: 41, v: 30, a: "تَتَنَزَّلُ عَلَيْهِمُ ٱلْمَلَـٰٓئِكَةُ أَلَّا تَخَافُوا۟ وَلَا تَحْزَنُوا۟", t: "The angels descend upon them: Do not fear and do not grieve.", th: "comfort" },
        { s: 9, v: 40, a: "إِنَّ ٱللَّهَ مَعَنَا", t: "Indeed Allah is with us.", th: "closeness" },
        { s: 33, v: 3, a: "وَتَوَكَّلْ عَلَى ٱللَّهِ", t: "Rely upon Allah.", th: "trust" },
        { s: 39, v: 10, a: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", t: "The patient get their reward without account.", th: "reward" },
        { s: 46, v: 15, a: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ", t: "My Lord, enable me to be grateful.", th: "dua" },
        { s: 29, v: 69, a: "لَنَهْدِيَنَّهُمْ سُبُلَنَا", t: "We will surely guide them to Our ways.", th: "guidance" }
    ],
    lonely: [
        { s: 2, v: 186, a: "فَإِنِّى قَرِيبٌ أُجِيبُ دَعْوَةَ ٱلدَّاعِ", t: "Indeed I am near. I respond to the supplicant.", th: "closeness" },
        { s: 20, v: 46, a: "لَا تَخَافَآ إِنَّنِى مَعَكُمَآ أَسْمَعُ وَأَرَىٰٓ", t: "Fear not. I am with you both; I hear and I see.", th: "comfort" },
        { s: 9, v: 40, a: "لَا تَحْزَنْ إِنَّ ٱللَّهَ مَعَنَا", t: "Do not grieve; indeed Allah is with us.", th: "companionship" },
        { s: 13, v: 28, a: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", t: "In the remembrance of Allah do hearts find rest.", th: "peace" },
        { s: 40, v: 60, a: "ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ", t: "Call upon Me; I will respond.", th: "dua" },
        { s: 93, v: 3, a: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", t: "Your Lord has not taken leave of you.", th: "comfort" },
        { s: 93, v: 5, a: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰٓ", t: "Your Lord will give you, and you will be satisfied.", th: "promise" },
        { s: 10, v: 62, a: "أَلَآ إِنَّ أَوْلِيَآءَ ٱللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", t: "The allies of Allah — no fear or grief for them.", th: "security" },
        { s: 41, v: 30, a: "تَتَنَزَّلُ عَلَيْهِمُ ٱلْمَلَـٰٓئِكَةُ أَلَّا تَخَافُوا۟ وَلَا تَحْزَنُوا۟", t: "Angels descend: Do not fear and do not grieve.", th: "comfort" },
        { s: 41, v: 31, a: "نَحْنُ أَوْلِيَآؤُكُمْ فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا وَفِى ٱلْـَٔاخِرَةِ", t: "We are your allies in this life and the Hereafter.", th: "support" },
        { s: 3, v: 173, a: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ", t: "Sufficient for us is Allah.", th: "trust" },
        { s: 2, v: 152, a: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ", t: "Remember Me; I will remember you.", th: "remembrance" },
        { s: 65, v: 3, a: "وَمَن يَتَوَكَّلْ عَلَى ٱللَّهِ فَهُوَ حَسْبُهُۥٓ", t: "Whoever relies upon Allah — He is sufficient.", th: "trust" },
        { s: 30, v: 21, a: "وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً", t: "And He placed between you affection and mercy.", th: "love" },
        { s: 49, v: 10, a: "إِنَّمَا ٱلْمُؤْمِنُونَ إِخْوَةٌ", t: "The believers are but brothers.", th: "brotherhood" },
        { s: 49, v: 13, a: "يَـٰٓأَيُّهَا ٱلنَّاسُ إِنَّا خَلَقْنَـٰكُم مِّن ذَكَرٍ وَأُنثَىٰ وَجَعَلْنَـٰكُمْ شُعُوبًا وَقَبَآئِلَ لِتَعَارَفُوٓا۟", t: "We created you from male and female and made you peoples and tribes to know one another.", th: "community" },
        { s: 12, v: 86, a: "إِنَّمَآ أَشْكُوا۟ بَثِّى وَحُزْنِىٓ إِلَى ٱللَّهِ", t: "I only complain of my suffering and grief to Allah.", th: "grief" },
        { s: 27, v: 62, a: "أَمَّن يُجِيبُ ٱلْمُضْطَرَّ إِذَا دَعَاهُ", t: "Is He not the One who responds to the distressed?", th: "dua" },
        { s: 21, v: 87, a: "لَّآ إِلَـٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ", t: "There is no deity except You; exalted are You.", th: "dua" },
        { s: 21, v: 88, a: "فَٱسْتَجَبْنَا لَهُۥ وَنَجَّيْنَـٰهُ مِنَ ٱلْغَمِّ", t: "So We responded and saved him from distress.", th: "rescue" },
        { s: 3, v: 139, a: "وَلَا تَهِنُوا۟ وَلَا تَحْزَنُوا۟", t: "Do not weaken and do not grieve.", th: "strength" },
        { s: 94, v: 5, a: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا", t: "With hardship comes ease.", th: "hope" },
        { s: 39, v: 53, a: "لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ", t: "Do not despair of Allah's mercy.", th: "mercy" },
        { s: 12, v: 87, a: "لَا تَا۟يْـَٔسُوا۟ مِن رَّوْحِ ٱللَّهِ", t: "Do not despair of relief from Allah.", th: "hope" },
        { s: 6, v: 17, a: "فَلَا كَاشِفَ لَهُۥٓ إِلَّا هُوَ", t: "None can remove it but Him.", th: "reliance" },
        { s: 7, v: 56, a: "إِنَّ رَحْمَتَ ٱللَّهِ قَرِيبٌ", t: "The mercy of Allah is near.", th: "mercy" },
        { s: 73, v: 8, a: "وَٱذْكُرِ ٱسْمَ رَبِّكَ وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا", t: "Remember your Lord's name and devote yourself.", th: "devotion" },
        { s: 20, v: 25, a: "رَبِّ ٱشْرَحْ لِى صَدْرِى", t: "My Lord, expand my chest.", th: "dua" },
        { s: 29, v: 69, a: "وَٱلَّذِينَ جَـٰهَدُوا۟ فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", t: "Those who strive for Us — We will guide them.", th: "guidance" },
        { s: 64, v: 11, a: "وَمَن يُؤْمِنۢ بِٱللَّهِ يَهْدِ قَلْبَهُۥ", t: "Whoever believes in Allah — He will guide his heart.", th: "guidance" },
        { s: 28, v: 24, a: "رَبِّ إِنِّى لِمَآ أَنزَلْتَ إِلَىَّ مِنْ خَيْرٍ فَقِيرٌ", t: "My Lord, I am in need of whatever good You send.", th: "humility" },
        { s: 94, v: 1, a: "أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ", t: "Did We not expand for you your breast?", th: "comfort" },
        { s: 57, v: 22, a: "مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا فِى كِتَـٰبٍ", t: "No disaster strikes except in a register.", th: "qadr" },
        { s: 9, v: 51, a: "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا", t: "Nothing befalls us except what Allah has written.", th: "qadr" },
        { s: 3, v: 8, a: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا", t: "Our Lord, let not our hearts deviate.", th: "dua" },
        { s: 23, v: 118, a: "رَّبِّ ٱغْفِرْ وَٱرْحَمْ", t: "My Lord, forgive and have mercy.", th: "dua" },
        { s: 33, v: 3, a: "وَتَوَكَّلْ عَلَى ٱللَّهِ", t: "Rely upon Allah.", th: "trust" },
        { s: 11, v: 88, a: "وَمَا تَوْفِيقِىٓ إِلَّا بِٱللَّهِ", t: "My success is only through Allah.", th: "trust" },
        { s: 14, v: 7, a: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", t: "If you are grateful, I will increase you.", th: "gratitude" },
        { s: 46, v: 15, a: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ", t: "My Lord, enable me to be grateful.", th: "dua" },
        { s: 39, v: 10, a: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", t: "The patient get their reward without account.", th: "reward" },
        { s: 8, v: 46, a: "وَٱصْبِرُوٓا۟ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ", t: "Be patient. Allah is with the patient.", th: "patience" },
        { s: 48, v: 4, a: "هُوَ ٱلَّذِىٓ أَنزَلَ ٱلسَّكِينَةَ فِى قُلُوبِ ٱلْمُؤْمِنِينَ", t: "He sent tranquility into the hearts of the believers.", th: "tranquility" },
        { s: 10, v: 58, a: "بِفَضْلِ ٱللَّهِ وَبِرَحْمَتِهِۦ فَبِذَٰلِكَ فَلْيَفْرَحُوا۟", t: "In Allah's bounty and mercy — let them rejoice.", th: "joy" },
        { s: 65, v: 2, a: "وَمَن يَتَّقِ ٱللَّهَ يَجْعَل لَّهُۥ مَخْرَجًا", t: "Whoever fears Allah — He will make a way out.", th: "tawakkul" }
    ],
    inspired: [
        { s: 96, v: 1, a: "ٱقْرَأْ بِٱسْمِ رَبِّكَ ٱلَّذِى خَلَقَ", t: "Read in the name of your Lord who created.", th: "knowledge" },
        { s: 55, v: 60, a: "هَلْ جَزَآءُ ٱلْإِحْسَـٰنِ إِلَّا ٱلْإِحْسَـٰنُ", t: "Is the reward for good anything but good?", th: "reward" },
        { s: 13, v: 11, a: "إِنَّ ٱللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا۟ مَا بِأَنفُسِهِمْ", t: "Allah will not change a people until they change themselves.", th: "action" },
        { s: 29, v: 69, a: "وَٱلَّذِينَ جَـٰهَدُوا۟ فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", t: "Those who strive for Us — We will guide them.", th: "striving" },
        { s: 2, v: 152, a: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ", t: "Remember Me; I will remember you.", th: "remembrance" },
        { s: 17, v: 9, a: "إِنَّ هَـٰذَا ٱلْقُرْءَانَ يَهْدِى لِلَّتِى هِىَ أَقْوَمُ", t: "This Quran guides to that which is most suitable.", th: "quran" },
        { s: 14, v: 7, a: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", t: "If you are grateful, I will increase you.", th: "gratitude" },
        { s: 94, v: 5, a: "فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا", t: "With hardship comes ease.", th: "resilience" },
        { s: 47, v: 7, a: "إِن تَنصُرُوا۟ ٱللَّهَ يَنصُرْكُمْ", t: "If you support Allah, He will support you.", th: "support" },
        { s: 6, v: 162, a: "قُلْ إِنَّ صَلَاتِى وَنُسُكِى وَمَحْيَاىَ وَمَمَاتِى لِلَّهِ", t: "My prayer, sacrifice, living, and dying are for Allah.", th: "devotion" },
        { s: 3, v: 159, a: "فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى ٱللَّهِ", t: "When you have decided, rely upon Allah.", th: "action" },
        { s: 103, v: 3, a: "وَتَوَاصَوْا۟ بِٱلْحَقِّ وَتَوَاصَوْا۟ بِٱلصَّبْرِ", t: "Urge each other to truth and patience.", th: "community" },
        { s: 16, v: 97, a: "مَنْ عَمِلَ صَـٰلِحًا فَلَنُحْيِيَنَّهُۥ حَيَوٰةً طَيِّبَةً", t: "Whoever does righteousness — We will give them a good life.", th: "reward" },
        { s: 93, v: 5, a: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰٓ", t: "Your Lord will give you, and you will be satisfied.", th: "promise" },
        { s: 40, v: 60, a: "ٱدْعُونِىٓ أَسْتَجِبْ لَكُمْ", t: "Call upon Me; I will respond.", th: "dua" },
        { s: 10, v: 58, a: "بِفَضْلِ ٱللَّهِ وَبِرَحْمَتِهِۦ فَبِذَٰلِكَ فَلْيَفْرَحُوا۟", t: "In Allah's bounty and mercy, let them rejoice.", th: "joy" },
        { s: 39, v: 53, a: "لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ", t: "Do not despair of Allah's mercy.", th: "mercy" },
        { s: 17, v: 70, a: "وَلَقَدْ كَرَّمْنَا بَنِىٓ ءَادَمَ", t: "We have honored the children of Adam.", th: "honor" },
        { s: 49, v: 13, a: "إِنَّ أَكْرَمَكُمْ عِندَ ٱللَّهِ أَتْقَىٰكُمْ", t: "The most noble of you is the most righteous.", th: "nobility" },
        { s: 57, v: 21, a: "سَابِقُوٓا۟ إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ", t: "Race toward forgiveness from your Lord.", th: "motivation" },
        { s: 3, v: 133, a: "وَسَارِعُوٓا۟ إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ", t: "Hasten to forgiveness and a garden wide as heavens and earth.", th: "motivation" },
        { s: 22, v: 78, a: "هُوَ ٱجْتَبَىٰكُمْ", t: "He has chosen you.", th: "chosen" },
        { s: 48, v: 1, a: "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا", t: "We have given you a clear conquest.", th: "victory" },
        { s: 24, v: 35, a: "ٱللَّهُ نُورُ ٱلسَّمَـٰوَاتِ وَٱلْأَرْضِ", t: "Allah is the Light of the heavens and earth.", th: "light" },
        { s: 93, v: 11, a: "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ", t: "As for the favor of your Lord, proclaim it.", th: "sharing" },
        { s: 41, v: 30, a: "إِنَّ ٱلَّذِينَ قَالُوا۟ رَبُّنَا ٱللَّهُ ثُمَّ ٱسْتَقَـٰمُوا۟", t: "Those who said 'Our Lord is Allah' and remained steadfast.", th: "steadfastness" },
        { s: 2, v: 186, a: "فَإِنِّى قَرِيبٌ", t: "Indeed I am near.", th: "closeness" },
        { s: 73, v: 20, a: "فَٱقْرَءُوا۟ مَا تَيَسَّرَ مِنَ ٱلْقُرْءَانِ", t: "Recite what is easy from the Quran.", th: "quran" },
        { s: 3, v: 173, a: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ", t: "Sufficient for us is Allah.", th: "trust" },
        { s: 65, v: 3, a: "وَمَن يَتَوَكَّلْ عَلَى ٱللَّهِ فَهُوَ حَسْبُهُۥٓ", t: "Whoever relies upon Allah — He is sufficient.", th: "trust" },
        { s: 13, v: 28, a: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", t: "In the remembrance of Allah do hearts find rest.", th: "peace" },
        { s: 76, v: 3, a: "إِنَّا هَدَيْنَـٰهُ ٱلسَّبِيلَ", t: "Indeed, We guided him to the way.", th: "guidance" },
        { s: 20, v: 114, a: "وَقُل رَّبِّ زِدْنِى عِلْمًا", t: "And say: My Lord, increase me in knowledge.", th: "knowledge" },
        { s: 96, v: 4, a: "ٱلَّذِى عَلَّمَ بِٱلْقَلَمِ", t: "Who taught by the pen.", th: "knowledge" },
        { s: 96, v: 5, a: "عَلَّمَ ٱلْإِنسَـٰنَ مَا لَمْ يَعْلَمْ", t: "Taught man that which he knew not.", th: "knowledge" },
        { s: 31, v: 27, a: "وَلَوْ أَنَّمَا فِى ٱلْأَرْضِ مِن شَجَرَةٍ أَقْلَـٰمٌ وَٱلْبَحْرُ يَمُدُّهُۥ مِنۢ بَعْدِهِۦ سَبْعَةُ أَبْحُرٍ مَّا نَفِدَتْ كَلِمَـٰتُ ٱللَّهِ", t: "If every tree on earth were a pen and the ocean ink, the words of Allah would not be exhausted.", th: "infinity" },
        { s: 2, v: 216, a: "وَعَسَىٰٓ أَن تَكْرَهُوا۟ شَيْـًٔا وَهُوَ خَيْرٌ لَّكُمْ", t: "Perhaps you hate a thing and it is good for you.", th: "wisdom" },
        { s: 8, v: 30, a: "وَيَمْكُرُونَ وَيَمْكُرُ ٱللَّهُ وَٱللَّهُ خَيْرُ ٱلْمَـٰكِرِينَ", t: "They plan, and Allah plans. Allah is the best of planners.", th: "trust" },
        { s: 12, v: 90, a: "إِنَّهُۥ مَن يَتَّقِ وَيَصْبِرْ فَإِنَّ ٱللَّهَ لَا يُضِيعُ أَجْرَ ٱلْمُحْسِنِينَ", t: "Whoever fears Allah and is patient — Allah doesn't waste the good-doers' reward.", th: "perseverance" },
        { s: 39, v: 10, a: "إِنَّمَا يُوَفَّى ٱلصَّـٰبِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", t: "The patient get their reward without account.", th: "reward" },
        { s: 46, v: 15, a: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ", t: "My Lord, enable me to be grateful.", th: "dua" },
        { s: 11, v: 88, a: "وَمَا تَوْفِيقِىٓ إِلَّا بِٱللَّهِ", t: "My success is only through Allah.", th: "humility" },
        { s: 3, v: 200, a: "ٱصْبِرُوا۟ وَصَابِرُوا۟ وَرَابِطُوا۟", t: "Be patient, endure, and remain stationed.", th: "endurance" },
        { s: 64, v: 11, a: "وَمَن يُؤْمِنۢ بِٱللَّهِ يَهْدِ قَلْبَهُۥ", t: "Whoever believes in Allah — He will guide his heart.", th: "guidance" },
        { s: 93, v: 3, a: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", t: "Your Lord has not taken leave of you.", th: "comfort" }
    ]
};

function expand(arr) { return arr.map(e => ({ surah: e.s, verse: e.v, arabicSnippet: e.a, translation: e.t, theme: e.th })); }
const merged = { ...existing };
for (const [mood, verses] of Object.entries(newMoods)) merged[mood] = expand(verses);
fs.writeFileSync(TARGET, JSON.stringify(merged, null, 4), 'utf8');
console.log('All moods:', Object.keys(merged).join(', '));
console.log('Total moods:', Object.keys(merged).length);
for (const [k, v] of Object.entries(merged)) console.log(`  ${k}: ${v.length} verses`);
